title = Superior over Canines 
description = Project trying to recreate/port Better than Wolves in Luanti.
min_minetest_version = 5.16.1
textdomain = game_description
aliases = Better than Wolves Lunati Port
author = Mercenary_lol
release = 1
