title = Superior over Canines 
description = A project to port Better than Eolves to Luanti engine.
min_minetest_version = 5.16.1
textdomain = game_description
aliases = Better than Wolves Lunati Port
author = Mercenary_lol
release = 1
