title = Superior over Canines 
description = i geniuely dont fucking know how you got access to this, its not even distributed anywhere so if you hacked me your a fucking piece of shit if youll delete this
min_minetest_version = 5.16.1
textdomain = game_description
aliases = Better than Wolves Lunati Port
author = Mercenary_lol
release = 1
